# Generated by Django 5.0.4 on 2024-05-03 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_faculty_desc_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('paper_title', models.CharField(max_length=200)),
                ('journal_name', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('page_no', models.PositiveIntegerField()),
                ('issue', models.DateField()),
                ('issn_no', models.PositiveIntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('impact_factor', models.CharField(max_length=250)),
                ('indexing', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
