# Generated by Django 5.0.4 on 2024-05-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_faculty_desc_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_desc',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
