# Generated by Django 5.0.4 on 2024-05-06 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_faculty_desc_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('paper_title', models.CharField(max_length=200)),
                ('conference_name', models.CharField(max_length=200)),
                ('proceeding', models.CharField(max_length=250)),
                ('year', models.PositiveIntegerField()),
                ('page_no', models.PositiveIntegerField()),
                ('issue', models.DateField()),
                ('issn_no', models.PositiveIntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('impact_factor', models.CharField(max_length=250)),
                ('indexing', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('duration_days', models.IntegerField(default=0)),
                ('duration_hours', models.IntegerField(default=0)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('organised_by', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('duration_days', models.IntegerField(default=0)),
                ('duration_hours', models.IntegerField(default=0)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('organised_by', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
