# Generated by Django 5.0.4 on 2024-05-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_conference_fdp_workshop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='author_name',
            new_name='c_author_name',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='conference_name',
            new_name='c_conference_name',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='impact_factor',
            new_name='c_impact_factor',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='indexing',
            new_name='c_indexing',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='issn_no',
            new_name='c_issn_no',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='issue',
            new_name='c_issue',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='page_no',
            new_name='c_page_no',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='paper_title',
            new_name='c_paper_title',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='proceeding',
            new_name='c_proceeding',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='publisher',
            new_name='c_publisher',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='year',
            new_name='c_year',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='duration_days',
            new_name='w_duration_days',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='duration_hours',
            new_name='w_duration_hours',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='faculty_name',
            new_name='w_faculty_name',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='from_date',
            new_name='w_from_date',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='organised_by',
            new_name='w_organised_by',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='to_date',
            new_name='w_to_date',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='topic',
            new_name='w_topic',
        ),
    ]
