# Generated by Django 5.0.4 on 2024-05-14 09:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_notices_circulars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices_circulars',
            name='notice_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
